apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
    - persistent-volume.yaml
    - persistent-volume-claim.yaml
    - deployment.yaml
    - service.yaml
secretGenerator:
    -   name: postgres-secret
        options:
            disableNameSuffixHash: true
        type: Opaque
        namespace: database
        files:
            - .secrets/POSTGRES_DB
            - .secrets/POSTGRES_USER
            - .secrets/POSTGRES_PASSWORD
