// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Password     string             `db:"password" json:"-"`
	Creation     pgtype.Timestamptz `db:"creation" json:"creation"`
	Modification pgtype.Timestamptz `db:"modification" json:"modification"`
	Deletion     pgtype.Timestamptz `db:"deletion" json:"deletion"`
}
