// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package overrides

type UserPermission struct {
	ID           int64 `db:"id" json:"id"`
	UserID       int64 `db:"user-id" json:"user-id"`
	PermissionID int64 `db:"permission-id" json:"permission-id"`
}
