apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
                version: v1
                sidecar.istio.io/inject: "true"
        spec:
            containers:
                -   name: redis
                    image: redis:7
                    imagePullPolicy: Always
                    command:
                        - redis-server
                        - "/redis-master/redis.conf"
                    ports:
                        -   containerPort: 6379

                    env:
                        -   name: MASTER
                            value: "true"
                    volumeMounts:
                        -   mountPath: /redis-master-data
                            name: data
                        -   mountPath: /redis-master
                            name: configuration
            volumes:
                -   name: data
                    emptyDir: { }
                -   name: configuration
                    configMap:
                        name: redis-configuration
                        items:
                            -   key: redis-config
                                path: redis.conf
