kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: development
images:
    - name: service:latest
      newName: localhost:5050/authentication-service
      newTag: 0.0.54
resources:
    - application.yaml
secretGenerator:
    - namespace: development
      name: authentication-service-postgres-secret
      files:
        - ./.secrets/PGUSER
        - ./.secrets/PGPASSWORD
        - ./.secrets/PGDATABASE
      options:
        disableNameSuffixHash: true
      type: Opaque
