---
apiVersion: v1
kind: Service
metadata:
    name: api # api.user-service.svc.cluster.local
    labels:
        app: api
        service: user-service
spec:
    selector:
        app: api
    ports:
        -   port: 8080
            targetPort: 8080
            name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: user-service
    labels:
        account: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
    labels:
        app: api
        version: v1
        service: user-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
            version: v1
            service: user-service
    template:
        metadata:
            labels:
                app: api
                version: v1
                service: user-service
                sidecar.istio.io/inject: "true"
        spec:
            serviceAccountName: user-service
            containers:
                -   name: api
                    livenessProbe:
                        httpGet:
                            port: 8080
                            path: /health
                        initialDelaySeconds: 5
                        periodSeconds: 30
                    image: service:latest
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 8080
                    envFrom:
                        -   secretRef:
                                name: postgres-application-secret
                    env:
                        -   name: CI
                            value: "true"
                        -   name: LOCAL_POD_SERVICE_ACCOUNT
                            valueFrom:
                                fieldRef:
                                    fieldPath: spec.serviceAccountName
                        -   name: LOCAL_POD_IP
                            valueFrom:
                                fieldRef:
                                    fieldPath: status.podIP
                        -   name: LOCAL_NODE_NAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: spec.nodeName
                        -   name: LOCAL_POD_NAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -   name: LOCAL_POD_NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -   name: LOCAL_NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -   name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -   name: VERSION
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.labels['version']
                        -   name: "PGHOST"
                            value: "postgres.user-service.svc.cluster.local"
                        -   name: "PGPORT"
                            value: "5432"
                        -   name: "PGTZ"
                            value: "UTC"
                        -   name: "PGAPPNAME"
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.labels['app']
                        -   name: "PGCONNECT_TIMEOUT"
                            value: "10"

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
    name: api
    labels:
        sidecar.istio.io/inject: "true"
spec:
    parentRefs:
        -   name: api-gateway
            kind: Gateway
            namespace: development
            group: "gateway.networking.k8s.io"
    rules:
        -   matches:
                -   path:
                        type: PathPrefix
                        value: /v1/users
            filters:
                -   type: URLRewrite
                    urlRewrite:
                        path:
                            type: ReplacePrefixMatch
                            replacePrefixMatch: /
                -   type: RequestHeaderModifier
                    requestHeaderModifier:
                        add:
                            -   name: "X-API-Version"
                                value: "v1"
            backendRefs:
                -   name: api
                    kind: Service
                    port: 8080

#---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#    name: gateway
#spec:
#    # Match the generated Deployment by reference
#    # Note: Do not use `kind: Gateway`.
#    scaleTargetRef:
#        apiVersion: apps/v1
#        kind: Deployment
#        name: gateway-istio
#    minReplicas: 2
#    maxReplicas: 5
#    metrics:
#        - type: Resource
#          resource:
#              name: cpu
#              target:
#                  type: Utilization
#                  averageUtilization: 50
#---
#apiVersion: policy/v1
#kind: PodDisruptionBudget
#metadata:
#    name: gateway
#spec:
#    minAvailable: 1
#    selector:
#        # Match the generated Deployment by label
#        matchLabels:
#            gateway.networking.k8s.io/gateway-name: gateway
