apiVersion: v1
kind: PersistentVolume
metadata:
    name: user-service-postgres-volume
    labels:
        type: local
        app: postgres
spec:
    storageClassName: manual
    persistentVolumeReclaimPolicy: Delete
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /data/postgres/16
