kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: development
images:
    - name: service:latest
      newName: localhost:5050/user-service
      newTag: 0.0.62
resources:
    - application.yaml
    - authorization-policy.yaml
secretGenerator:
    - namespace: development
      name: user-service-postgres-secret
      files:
        - ./.secrets/PGUSER
        - ./.secrets/PGPASSWORD
        - ./.secrets/PGDATABASE
      options:
        disableNameSuffixHash: true
      type: Opaque
