// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package associations

type RolePermission struct {
	ID           int64 `db:"id" json:"id"`
	RoleID       int64 `db:"role-id" json:"role-id"`
	PermissionID int64 `db:"permission-id" json:"permission-id"`
}

type UserRole struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user-id" json:"user-id"`
	RoleID int64 `db:"role-id" json:"role-id"`
}
