// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package roles

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID           int64              `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Description  *string            `db:"description" json:"description"`
	Creation     pgtype.Timestamptz `db:"creation" json:"creation"`
	Modification pgtype.Timestamptz `db:"modification" json:"modification"`
	Deletion     pgtype.Timestamptz `db:"deletion" json:"deletion"`
}
