// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package roles

import (
	"context"
)

type Querier interface {
	// Roles returns all Role record(s).
	Roles(ctx context.Context) ([]*Role, error)
}

var _ Querier = (*Queries)(nil)
