// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package overrides

import (
	"context"
)

type Querier interface {
	// UserPermissions returns all UserPermission record(s).
	UserPermissions(ctx context.Context) ([]*UserPermission, error)
}

var _ Querier = (*Queries)(nil)
