// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package permissions

import (
	"context"
)

type Querier interface {
	// Permissions returns all Permission record(s).
	Permissions(ctx context.Context) ([]*Permission, error)
}

var _ Querier = (*Queries)(nil)
