apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    -   namespace.yaml
secretGenerator:
    -   name: aws-external-secrets-provider
        options:
            disableNameSuffixHash: true
        type: Opaque
        namespace: flux-system
        files:
            - .secrets/aws-access-key-id
            - .secrets/aws-secret-access-key
