apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    creationTimestamp: "2024-05-23T17:51:53Z"
    generation: 1
    labels:
        helm.toolkit.fluxcd.io/name: kiali-operator
        helm.toolkit.fluxcd.io/namespace: istio-system
    name: kialis.kiali.io
    resourceVersion: "423470"
    uid: d726af2f-1d71-450e-ba5e-d14e619a8e2d
spec:
    conversion:
        strategy: None
    group: kiali.io
    names:
        kind: Kiali
        listKind: KialiList
        plural: kialis
        singular: kiali
    scope: Namespaced
    versions:
        - name: v1alpha1
          schema:
              openAPIV3Schema:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
          served: true
          storage: true
          subresources:
              status: {}
status:
    acceptedNames:
        kind: Kiali
        listKind: KialiList
        plural: kialis
        singular: kiali
    conditions:
        - lastTransitionTime: "2024-05-23T17:51:53Z"
          message: no conflicts found
          reason: NoConflicts
          status: "True"
          type: NamesAccepted
        - lastTransitionTime: "2024-05-23T17:51:53Z"
          message: the initial names have been accepted
          reason: InitialNamesAccepted
          status: "True"
          type: Established
    storedVersions:
        - v1alpha1
